### ISSUE TITLE
Update Request: Disable Bus Slot Selection After Departure Time

### ISSUE THREAD

**Issue by A-fethi** [HamzaElAzzouzi/Transport01-report#1]
![Screenshot from 2024-09-26 18-12-49](https://github.com/user-attachments/assets/76cab0ef-328f-49ef-abc7-47a2455fd811)
First of all, Thank you for your hard work on this Web App. I believe it’s important to provide an update to ensure that once the bus time has passed, that selected slot is no longer available. This will help us maintain clarity and avoid any confusion.

**Comment by Hamza-El-Azzouzi** [comment]
it's will be in next update 
thank you for reporting and your feedback

**Comment by Hamza-El-Azzouzi** [comment]
now it fixed
